food/urls.py
from django.urls import path
from . import views
app_name = 'food'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('list/', views.list, name = 'list'),
    path('list/create/', views.listcreate, name = 'listcreate'),
    path('list/delete/<int:id>', views.listdelete , name ='listdelete'),
    path('list/update/<int:id>', views.listupdate , name = 'listupdate'),
    # path('list/chart/', views.listchart , name = 'listchart'), 
    path('list/search/', views.listsearch , name = 'listsearch'),
    path('record/', views.record, name = 'record'),
    path('record_ajax/', views.record_ajax , name = 'record_ajax'),
    path('record/create/', views.recordcreate , name ='recordcreate'),
    path('record/delete/<int:id>', views.recorddelete , name ='recorddelete'),
    path('record/update/<int:id>', views.recordupdate , name = 'recordupdate'),
    path('record/chart/', views.recordchart , name = 'recordchart'),
    path('datatosql', views.datatosql),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'base'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.real, name = 'about'),
    path('contant/', views.hay, name = 'contact'),
]

lifemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter,url
from memorf import views as mviews
from limit import views as lview
from sport import views as sview
from on_accountapi import views as oaview
from foodrestful import views as fviews

# Router
router = DefaultRouter()

router.register(r'memorf',mviews.MemorfViewSet)
#limit
router.register(r'user',lview.UserViewSet)
router.register(r'userrole',lview.UserRoleViewSet)
#sport
router.register(r'sportitem',sview.SportItemViewSet)
router.register(r'sportrecord',sview.SportRecordViewSet)
# on_accountapi
router.register(r'on_accountapi',oaview.On_AccountapiViewSet)
#food
router.register(r'foodrestfulFC', fviews.FoodCategoryApiViewSet)
router.register(r'foodrestfulFL', fviews.FoodListApiViewSet)
# #不指定直接回傳
# router.register(r'foodrestfulDR', fviews.DietaryRecordApiViewSet)


# URL
urlpatterns = [
    #改用url指定路徑回傳指定資料，並將DietaryRecordApiViewSet當成views呼叫
    url(r'foodrestfulDR\/(?P<userid>.+)\/(?P<sdate>.+)\/(?P<edate>.+)\/$', fviews.DietaryRecordApiViewSet.as_view()),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('home.urls')),
    path('memo/', include('memo.urls')),
    path('limit/',include('limit.urls')),
    path('sport/',include('sport.urls')),
    path('on_account/', include('on_account.urls')),
    path('food/', include('food.urls')),
]

memo/urls.py
from django.urls import path
from memo import views

app_name='memo'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('update/<int:id>',views.update,name='update'),
    path('archive/',views.archive,name='archive'),
    path('chartpie/', views.chartPie, name = 'chartpie'),
    path('chartdata/<str:s_date>/<str:e_date>/', views.chartData, name = 'chartdata'),
]

on_account/urls.py
from django.urls import path
from . import views

app_name = 'on_account'
urlpatterns = [
    path('', views.index, name = 'index'),

    path('chatarea/',views.chatarea,name="chatarea"),

    path('catch/',views.catchid,name="catchid"),
]

sport/urls.py
from django.urls import path
from . import views

app_name = 'sport'

urlpatterns = [

    path('',views.item, name = 'sportitem'),
    path('sportrecord/', views.record, name = 'sportrecord'),
    path('itemscraping/', views.itemScraping, name = 'itemscraping'),
    path('chartpie/', views.chartPie, name = 'chartpie'),
    path('chartdata/<str:s_date>/<str:e_date>/', views.chartData, name = 'chartdata'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    title = 'cool'
    return render(request, 'home/index.html', locals())
def real(request):
    time = datetime.datetime.now()
    return render(request, 'home/about.html', locals())
def hay(request):
    users = [{'name':'Jack', 'age':30, 'email':'jack@gmail.com'},
             {'name':'Tom', 'age':30, 'email':'tom@gmail.com'},
             {'name':'Luka', 'age':30, 'email':'luka@gmail.com'},]
    return render(request, 'home/ontact.html', locals())

home/templates/home/homeNav.html
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa fa-fw fa-home"></i>
            <span>首頁</span>
        </a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'memo:index' %}">
            <i class="fa fa-fw fa-list"></i>
            <span>代辦事項</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'on_account:index' %}">
            <i class="fa fa-fw fa-clipboard-list"></i>
            <span>家計簿</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'food:index' %}">
            <i class="fa fa-fw fa-utensils"></i>
            <span>健康資訊</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'sport:sportrecord' %}">
            <i class="fa fa-fw fa-walking"></i>
            <span>運動管理</span></a>
    </li>
</ul>

home/templates/home/index.html
{% extends 'base.html' %}

{% block styles %}
<style>
    .word {
        height: 300px;
        cursor: pointer;
    }

    .card {
        display: inline-block;
        margin: 20px;
    }

    .body {
        width: 100%;
        height: 758px;
        background-image: url(static/images/bg.jpg);
    }
</style>
{% endblock %}

{% block left %}
{% include "./homeNav.html" %}
{% endblock %}


{% block main %}
<div class="card-body body">
    <a href="{% url 'memo:index' %}"><img class="word" src="static/images/book.png"></a>
    <a href="{% url 'on_account:index' %}"><img class="word" src="static/images/wealth.png"></a>
    <a href="{% url 'food:index' %}"><img class="word" src="static/images/food.png"></a>
    <a href="{% url 'sport:sportrecord' %}"><img class="word" src="static/images/physic.png"></a>
</div>
{% endblock %}


{% block scripts %}
<script src="/static/scripts/jquery-3.3.1.min.js"></script>
<script>
    $('img').hover(function () {
        $(this).fadeTo(500, 0.3)
    }, function () {
        $(this).fadeTo(500, 1)
    })
</script>

{% endblock %}