food/urls.py
from django.urls import path
from . import views
app_name = 'food'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('list/', views.list, name = 'list'),
    path('list/create/', views.listcreate, name = 'listcreate'),
    path('list/delete/<int:id>', views.listdelete , name ='listdelete'),
    path('list/update/<int:id>', views.listupdate , name = 'listupdate'),
    # path('list/chart/', views.listchart , name = 'listchart'), 
    path('list/search/', views.listsearch , name = 'listsearch'),
    path('record/', views.record, name = 'record'),
    path('record_ajax/', views.record_ajax , name = 'record_ajax'),
    path('record/create/', views.recordcreate , name ='recordcreate'),
    path('record/delete/<int:id>', views.recorddelete , name ='recorddelete'),
    path('record/update/<int:id>', views.recordupdate , name = 'recordupdate'),
    path('record/chart/', views.recordchart , name = 'recordchart'),
    path('datatosql', views.datatosql),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'base'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.real, name = 'about'),
    path('contant/', views.hay, name = 'contact'),
]

lifemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter,url
from memorf import views as mviews
from limit import views as lview
from sport import views as sview
from on_accountapi import views as oaview
from foodrestful import views as fviews

# Router
router = DefaultRouter()

router.register(r'memorf',mviews.MemorfViewSet)
#limit
router.register(r'user',lview.UserViewSet)
router.register(r'userrole',lview.UserRoleViewSet)
#sport
router.register(r'sportitem',sview.SportItemViewSet)
router.register(r'sportrecord',sview.SportRecordViewSet)
# on_accountapi
router.register(r'on_accountapi',oaview.On_AccountapiViewSet)
#food
router.register(r'foodrestfulFC', fviews.FoodCategoryApiViewSet)
router.register(r'foodrestfulFL', fviews.FoodListApiViewSet)
# #不指定直接回傳
# router.register(r'foodrestfulDR', fviews.DietaryRecordApiViewSet)


# URL
urlpatterns = [
    #改用url指定路徑回傳指定資料，並將DietaryRecordApiViewSet當成views呼叫
    url(r'foodrestfulDR\/(?P<userid>.+)\/(?P<sdate>.+)\/(?P<edate>.+)\/$', fviews.DietaryRecordApiViewSet.as_view()),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('home.urls')),
    path('memo/', include('memo.urls')),
    path('limit/',include('limit.urls')),
    path('sport/',include('sport.urls')),
    path('on_account/', include('on_account.urls')),
    path('food/', include('food.urls')),
]

food/models.py
from django.db import models
from limit.models import User

# Create your models here.
class FoodCategory(models.Model):
    foodcategoryid = models.AutoField(primary_key=True)
    foodcategory = models.CharField(max_length=50)
    class Meta:
        db_table = "foodcategorys"

class FoodList(models.Model):
    foodid = models.AutoField(primary_key=True)
    foodcategoryid = models.ForeignKey(FoodCategory,models.DO_NOTHING,db_column='foodcategoryid')
    foodname = models.CharField(max_length=50)
    foodcalories = models.FloatField(null=True)
    foodprotein = models.FloatField(null=True)
    foodfat = models.FloatField(null=True)
    foodfarbohydrate = models.FloatField(null=True)
    fooddescription = models.CharField(max_length=500,null=True)
    userid = models.ForeignKey(User,models.DO_NOTHING,db_column='userid',null=True)
    class Meta:
        db_table = "footlists"

class DietaryRecord(models.Model):
    recordid = models.AutoField(primary_key=True)
    dietarydate = models.DateField()
    dietarytime = models.CharField(max_length=50)
    foodid = models.ForeignKey(FoodList,models.DO_NOTHING,db_column='foodid')
    share = models.FloatField(null=True)
    calories = models.FloatField(null=True)
    userid = models.ForeignKey(User,models.DO_NOTHING,db_column='userid',null=True)
    class Meta:
        db_table = "dietaryrecords"
     
  

food/views.py
from django.shortcuts import render,redirect
# from food.models import FoodList,FoodCategory,DietaryRecord
from foodrestful.models import FoodListApi,FoodCategoryApi,DietaryRecordApi
from limit.models import User
from django.http import HttpResponse
import json
from django.core import serializers


foodcategorys = FoodCategoryApi.objects.all()
foodlists = FoodListApi.objects.all()
dietaryrecords = DietaryRecordApi.objects.all()

#================================會員登入=============================================

# function desc. : 確認使用者是否登入
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/10/07
def chklogin(request):
    if('userid' in request.session):
        global userid
        global username
        userid = request.session["userid"]
        username = request.COOKIES["name"]
        return 0
    else:
        return 1


# ================================index===============================================

#回傳食物應用程式首頁
def index(request):
    return render(request, 'food/index.html', locals())


# ================================list=================================================

#回傳食物清單
def list(request):
    # print(request.path)
    # 確認是否已登入會員
    # cookies中沒有name表示沒有登入過
    # 轉到登入頁面
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    # ---------------------------------------------------------------------------------
        
    foodlists = FoodListApi.objects.all()
    
    return render(request, 'food/foodlist.html', locals())


#食物清單新增ORM
def listcreate(request):
    # print(request.path)
    # 確認是否已登入會員
    # cookies中沒有name表示沒有登入過
    # 轉到登入頁面
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    # --------------------------------------------------------------------------------  

    #步驟二
    if  request.method == "POST":
        #接收表單傳過來的資料
        foodcategoryid = request.POST["foodcategoryid"]
        foodname = request.POST["foodname"]
        foodcalories = request.POST["foodcalories"]
        foodprotein = request.POST["foodprotein"]
        foodfat = request.POST["foodfat"]
        foodfarbohydrate = request.POST["foodfarbohydrate"]
        fooddescription = request.POST["fooddescription"]
        #建立人員~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        user = User.objects.get(id=userid)
        #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        #將資料寫進資料庫
        FoodListApi.objects.create(foodcategoryid=FoodCategoryApi.objects.get(foodcategoryid=foodcategoryid),foodname=foodname,foodcalories=foodcalories,foodprotein=foodprotein,foodfat=foodfat,foodfarbohydrate=foodfarbohydrate,fooddescription=fooddescription,userid=user)
    
        return redirect('/food/list')
   
    #步驟一 GET 回傳空白的表單

    foodcategorys = FoodCategoryApi.objects.all()
    
    return render(request, 'food/listcreate.html', locals())


#食物清單刪除ORM
def listdelete(request,id):
    # print(request.path)
    # 確認是否已登入會員
    # cookies中沒有name表示沒有登入過
    # 轉到登入頁面
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    # --------------------------------------------------------------------------------  

    foodlist = FoodListApi.objects.get(foodid=id)
    foodlist.delete()

    return redirect('/food/list')


#食物清單修改ORM
def listupdate(request,id):
    # print(request.path)
    # 確認是否已登入會員
    # cookies中沒有name表示沒有登入過
    # 轉到登入頁面
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    # --------------------------------------------------------------------------------  

    #步驟二
    if  request.method == "POST":
        #接收表單傳過來的資料
        foodcategoryid = request.POST["foodcategoryid"]
        foodname = request.POST["foodname"]
        foodcalories = request.POST["foodcalories"]
        foodprotein = request.POST["foodprotein"]
        foodfat = request.POST["foodfat"]
        foodfarbohydrate = request.POST["foodfarbohydrate"]
        fooddescription = request.POST["fooddescription"]
        
        #將資料寫進資料庫
        foodlist = FoodListApi.objects.get(foodid=id)
        foodlist.foodcategoryid = FoodCategoryApi.objects.get(foodcategoryid=foodcategoryid)
        foodlist.foodname = foodname
        foodlist.foodcalories = foodcalories
        foodlist.foodprotein = foodprotein
        foodlist.foodfat = foodfat
        foodlist.foodfarbohydrate = foodfarbohydrate
        foodlist.fooddescription = fooddescription
        foodlist.save()
        return redirect('/food/list')

    #步驟一 GET 回傳空白的表單
    
    foodcategorys = FoodCategoryApi.objects.all()

    return render(request,'food/listupdate.html',locals())


# # 食物清單圖表ORM
# def listchart(request):
#     return render(request,'food/foodlistchart.html',locals())


#食物清單搜尋(ORM+ajax版) 
def listsearch(request):
    search = request.GET["search"] 
    categorys = FoodCategoryApi.objects.filter(foodcategory__contains=search)
    foodlists_name = FoodListApi.objects.filter(foodname__contains=search)
    foodlists_calories = FoodListApi.objects.filter(foodcalories__contains=search)
    json_datas = ''
    datas = []
    #判斷search是否為空值
    if search:
        if categorys:
            # datas = []
            for category in categorys:
                foodlists_category=FoodListApi.objects.filter(foodcategoryid=category.foodcategoryid)
                for foodlist in foodlists_category:
                    foodid = foodlist.foodid
                    foodname = foodlist.foodname
                    foodcategoryid = foodlist.foodcategoryid.foodcategoryid
                    foodcategory = foodlist.foodcategoryid.foodcategory
                    foodcalories =  foodlist.foodcalories
                    foodprotein = foodlist.foodprotein
                    foodfat = foodlist.foodfat
                    foodfarbohydrate = foodlist.foodfarbohydrate
                    fooddescription = foodlist.fooddescription
                    data={"foodid":foodid,"foodname":foodname,"foodcategoryid":foodcategoryid,"foodcategory":foodcategory,
                        "foodcalories":foodcalories,"foodprotein":foodprotein,"foodfat":foodfat,
                        "foodfarbohydrate":foodfarbohydrate,"fooddescription":fooddescription}
                    datas.append(data)
            # json_datas = json.dumps(datas)
            # json_datas = serializers.serialize("json",datas)
            # return HttpResponse(json_datas)
        
        if foodlists_name:
            # datas = []
            for foodlist in foodlists_name:
                foodid = foodlist.foodid
                foodname = foodlist.foodname
                foodcategoryid = foodlist.foodcategoryid.foodcategoryid
                foodcategory = foodlist.foodcategoryid.foodcategory
                foodcalories =  foodlist.foodcalories
                foodprotein = foodlist.foodprotein
                foodfat = foodlist.foodfat
                foodfarbohydrate = foodlist.foodfarbohydrate
                fooddescription = foodlist.fooddescription
                #判斷datas裡有沒有資料
                #如果datas有資料
                if datas:
                    unappended = True
                    for food in datas:
                        #如果datas裡已經有此筆資料把unappended改成False並離開迴圈
                        if food["foodid"] == foodid:
                            unappended = False
                            break
                    #如果unappended是True把資料加進去
                    if unappended:
                        data={"foodid":foodid,"foodname":foodname,"foodcategoryid":foodcategoryid,"foodcategory":foodcategory,
                            "foodcalories":foodcalories,"foodprotein":foodprotein,"foodfat":foodfat,
                            "foodfarbohydrate":foodfarbohydrate,"fooddescription":fooddescription}
                        datas.append(data)     
                #如果datas沒有資料直接加進去
                else: 
                    data={"foodid":foodid,"foodname":foodname,"foodcategoryid":foodcategoryid,"foodcategory":foodcategory,
                        "foodcalories":foodcalories,"foodprotein":foodprotein,"foodfat":foodfat,
                        "foodfarbohydrate":foodfarbohydrate,"fooddescription":fooddescription}
                    datas.append(data)
            # json_datas = json.dumps(datas)
            # json_datas = serializers.serialize("json",datas)
            # return HttpResponse(json_datas)

        if  foodlists_calories:  
            # datas = []
            for foodlist in foodlists_calories:
                foodid = foodlist.foodid
                foodname = foodlist.foodname
                foodcategoryid = foodlist.foodcategoryid.foodcategoryid
                foodcategory = foodlist.foodcategoryid.foodcategory
                foodcalories =  foodlist.foodcalories
                foodprotein = foodlist.foodprotein
                foodfat = foodlist.foodfat
                foodfarbohydrate = foodlist.foodfarbohydrate
                fooddescription = foodlist.fooddescription
                if datas:
                    unappended = True
                    for food in datas:
                        if food["foodid"] == foodid:
                            unappended = False
                            break
                    if unappended:
                        data={"foodid":foodid,"foodname":foodname,"foodcategoryid":foodcategoryid,"foodcategory":foodcategory,
                            "foodcalories":foodcalories,"foodprotein":foodprotein,"foodfat":foodfat,
                            "foodfarbohydrate":foodfarbohydrate,"fooddescription":fooddescription}
                        datas.append(data)   

food/templates/food/dietaryrecord.html
{% extends "base.html" %}
{% block styles %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="/static/styles/jquery-Datepicker.css">
{% endblock %}

{% block left %}

<ul class="sidebar navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'base:index' %}">
                <i class="fa fa-fw fa-home"></i>
                <span>首頁</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:list' %}">
                <i class="fas fa-utensils"></i>
                <span>食物查詢</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record' %}">
                <i class="fas fa-user-edit"></i>
                <span>飲食紀錄1</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record_ajax' %}">
                 <i class="fas fa-user-edit"></i>
                <span>飲食紀錄2</span>
            </a>
        </li>
    </ul>

{% endblock %}
{% block main %}
<div class="container">
    <div>
        <a href="{% url 'food:recordcreate' %}" class="btn btn-success"><i class="fas fa-plus-circle"></i>新增紀錄</a>
        <a href="{% url 'food:recordchart' %}" class="btn btn-info"><i class="fas fa-chart-pie"></i>查看圖表</a>
        <!-- 自己做的搜尋============================================================= -->
        
        <!-- <div style="display:inline-block ; float:right">
        <div class="input-group">
        <input type="text"  id="inputrecord" placeholder="Search" name="recordsearch">
        <div class="input-group-append" >
            <button type="submit" class="btn btn-primary" name="search"><i class="fa fa-search">搜尋</button>   
        </div>
        </div>
        </div> -->

        <!-- ========================================================================= -->
    </div>
    <hr>
    <table id="myDataTalbe" class="table table-bordered">
         <!-- 時間查詢================================================================ -->

        <p id="date_filter">
            <span id="date-label-from">開始時間:</span><input class="date" type="text" id="datepicker_from"/>
            <span id="date-label-to">&sim;結束時間:<input class="date" type="text" id="datepicker_to"/>
        </p>
    
        <!-- ======================================================================= -->
        <thead>
            <tr>
                <th>日期</th>
                <th>時間</th>
                <th>食物類別</th>
                <th>食物名稱</th>
                <th>份數(每100克)</th>
                <th>熱量(kcal)</th>
                <th>編輯</th>
            </tr>
        </thead>
            {% for dietaryrecord in dietaryrecords %}
            <tr>
                <td contenteditable=true>{{dietaryrecord.dietarydate|date:"Y-m-d"}}</td>
                <td contenteditable=true>{{dietaryrecord.dietarytime}}</td>
                <td contenteditable=true>{{dietaryrecord.foodid.foodcategoryid.foodcategory}}</td>
                <td contenteditable=true>{{dietaryrecord.foodid.foodname}}</td>
                <td contenteditable=true>{{dietaryrecord.share}}</td>
                <td contenteditable=true>{{dietaryrecord.calories}}</td>
                <td>
                    <a href="{% url 'food:recorddelete' dietaryrecord.recordid %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i>刪除</a>
                    <a href="{% url 'food:recordupdate' dietaryrecord.recordid %}" class="btn btn-secondary"><i class="fas fa-user-edit"></i>修改</a>
                </td>
            </tr>
            {% endfor %}
        <thead>
      
        </thead>
    </table>
</div>    
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
{% load static %}
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/jquery-Datepicker.js' %}"></script>
<script src="{% static 'scripts/jquery-dateformat.min.js' %}"></script>
 



<script type="text/javascript">
  


$(document).ready(function () { 
    

// 表格套件========================================================================

    var table = $("#myDataTalbe").DataTable({
                    searching: true, //關閉filter功能
                    columnDefs: [{
                    targets: [6],
                    orderable: false,
                    }]
                }); 


// 時間查詢=========================================================================

  // function desc. :初始化運動時間區間查詢的日期選擇器並建立事件
  // parameter : 
  // create user : Luffy Lin
  // modify user : Luffy Lin
  // modify date : 2018/10/05
 
  $(".date").datepicker({
    showOn: "button",
    buttonImage: "/static/images/calender.png",
    buttonImageOnly: true,
    dateFormat: "yy-mm-dd",
    
  }).change(function () {
    table.draw();
  })


  // function desc. :日期區間-datatable filter
  // parameter : 
  // create user : Luffy Lin
  // modify user : Luffy Lin
  // modify date : 2018/09/21
  $.fn.dataTable.ext.search.push(function (settings, data, dataIndex) {
      var min = moment($('#datepicker_from').val())
      var max = moment($('#datepicker_to').val())
      var date = moment(data[0])

      if (min && !isNaN(min)) {
        if (date < min) {return false}
      }
      if (max && !isNaN(max)) {
        if (date > max) {return false}
      }
      return true; 
  });

})

</script>


<!-- ajax的新刪修查=================================================================== -->


<script>




</script>


{% endblock %}

food/templates/food/foodlist.html
{% extends "base.html" %}
{% block styles %}
<style>
.content{
    display:none
}
p{
    color: red;
    font-size: 15px;
    font-weight: 900;
}
</style>
{% endblock %}

{% block left %}

<ul class="sidebar navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'base:index' %}">
                <i class="fa fa-fw fa-home"></i>
                <span>首頁</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:list' %}">
                <i class="fas fa-utensils"></i>
                <span>食物查詢</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record' %}">
                <i class="fas fa-user-edit"></i>
                <span>飲食紀錄1</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record_ajax' %}">
                 <i class="fas fa-user-edit"></i>
                <span>飲食紀錄2</span>
            </a>
        </li>
    </ul>
    
{% endblock %}
{% block main %}
<div class="container">
    <div>
        <div style="display:inline-block">
        <div class="input-group">
        <input type="text"  id="inputlist" placeholder="Search" name="listsearch">
        <div class="input-group-append" >
            <button type="submit" class="btn btn-primary" name="search"><i class="fa fa-search"></i>搜尋</button>
        </div>
        <p>*本資料庫所列數值單位均為每100g可食部分之含量</p>
        </div>
        </div>
        <!-- {% comment %}
        <a href="{% url 'food:listchart' %}" class="btn btn-info" style="margin-left:270px"><i class="fas fa-chart-pie"></i>查看圖表</a>
        {% endcomment %} -->
        <a href="{% url 'food:listcreate' %}" class="btn btn-success" style="float:right"><i class="fas fa-plus-circle"></i>新增食物</a>
    </div>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>食物類別</th>
                <th>食物名稱(每份=100公克)</th>
                <th>熱量(kcal)</th>
                <th>內容</th>
                <th>編輯</th>   
            </tr>
        </thead>
        <tbody>
        {% for foodlist in foodlists %}
            <tr>
                <td>{{foodlist.foodcategoryid.foodcategory}}</td>
                <td>{{foodlist.foodname}}</td>
                <td>{{foodlist.foodcalories}}</td>
                <td>
                    <button type="submit" class="btn btn-warning" name="details"><i class="fas fa-info-circle"></i>詳細資料</button>
                </td>
                <td>
                    <a href="{% url 'food:listdelete' foodlist.foodid %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i>刪除</a>
                    <a href="{% url 'food:listupdate' foodlist.foodid %}" class="btn btn-secondary"><i class="fas fa-user-edit"></i>修改</a>
                </td>
            </tr>
            <tr class='content'>
                <td colspan="5">
                每分含量：蛋白質(g)：{{foodlist.foodprotein}}、脂肪(g)：{{foodlist.foodfat}}、碳水化合物(g)：{{foodlist.foodfarbohydrate}}<br>
                描述：{{foodlist.fooddescription}}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>    
{% endblock %}
{% block scripts %}
<script>
// 當網頁讀取事件發生時觸發此function    
$(document).ready(function(){
// 按下詳細資料按鈕的事件發生時
    // $("button[name='details']").click(function(){
    //     $(this).parents("tr").next().toggle()
    // })
    $("tbody").on("click","button[name='details']",function(){
        $(this).parents("tr").next().toggle()
    })
//按下搜尋按鈕時
    $("button[name='search']").click(function(){
        var search = $('#inputlist').val()
        $.get('search/',{"search":search},function(jsonstr_datas){
            // console.log(jsonstr_datas)
        if(jsonstr_datas=="[]"){
            alert("查無此資料")
        }else{
            $("tbody > tr").remove()
            jsonobj_datas = JSON.parse(jsonstr_datas)
            // console.log(jsonobj_datas.length)
            for(i=0;i<jsonobj_datas.length;i++){
                $('tbody').append(
                "<tr>"+
                "<td>"+jsonobj_datas[i].foodcategory+"</td>"+
                "<td>"+jsonobj_datas[i].foodname+"</td>"+
                "<td>"+jsonobj_datas[i].foodcalories+"</td>"+
                "<td>"+"<button type='submit' class='btn btn-warning' name='details' >"+"<i class='fas fa-info-circle'>"+"</i>"+"詳細資料"+"</button>"+"</td>"+
                "<td>"+
                    "<a href='/food/list/delete/"+jsonobj_datas[i].foodid+ "' class='btn btn-danger'>"+"<i class='fas fa-trash-alt'>"+"</i>"+"刪除"+"</a>"+
                    "<a href='/food/list/update/" +jsonobj_datas[i].foodid+"' class='btn btn-secondary'>"+"<i class='fas fa-user-edit'>"+"</i>"+"修改"+"</a>"+
                "</td>"+
                "</tr>"+
                "<tr class='content'>"+
                    "<td colspan='5'>"+
                    "每分含量：蛋白質(g)："+jsonobj_datas[i].foodprotein+"、脂肪(g)："+jsonobj_datas[i].foodfat+"、碳水化合物(g)："+jsonobj_datas[i].foodfarbohydrate+"<br>"+
                    "描述："+jsonobj_datas[i].fooddescription+
                    "</td>"+
                "</tr>"
                )
            }
        }
        })
    })        
})
</script>
{% endblock %}

food/templates/food/foodlistchart.html
{% extends "base.html" %}
{% block styles %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
{% endblock %}

{% block left %}

<ul class="sidebar navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'base:index' %}">
                <i class="fa fa-fw fa-home"></i>
                <span>首頁</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:list' %}">
                <i class="fas fa-utensils"></i>
                <span>食物查詢</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record' %}">
                <i class="fas fa-user-edit"></i>
                <span>飲食紀錄1</span>
            </a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'food:record_ajax' %}">
                 <i class="fas fa-user-edit"></i>
                <span>飲食紀錄2</span>
            </a>
        </li>
    </ul>
    
{% endblock %}
{% block main %}
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
{% endblock %}
{% block scripts %}
<script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script src="https://canvasjs.com/assets/script/jquery.canvasjs.min.js"></script>
<script>
window.onload = function () {

    var options = {
        title: {
            text: "Desktop OS Market Share in 2017"
        },
        subtitles: [{
            text: "As of November, 2017"
        }],
        animationEnabled: true,
        data: [{
            type: "pie",
            startAngle: 40,
            toolTipContent: "<b>{label}</b>: {y}%",
            showInLegend: "true",
            legendText: "{label}",
            indexLabelFontSize: 16,
            indexLabel: "{label} - {y}%",
            dataPoints: [
                { y: 48.36, label: "Windows 7" },
                { y: 26.85, label: "Windows 10" },
                { y: 1.49, label: "Windows 8" },
                { y: 6.98, label: "Windows XP" },
                { y: 6.53, label: "Windows 8.1" },
                { y: 2.45, label: "Linux" },
                { y: 3.32, label: "Mac OS X 10.12" },
                { y: 4.03, label: "Others" }
            ]
        }]
    };
    $("#chartContainer").CanvasJSChart(options);
    
    }
</script>
{% endblock %}