food/urls.py
from django.urls import path
from . import views
app_name = 'food'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('list/', views.list, name = 'list'),
    path('list/create/', views.listcreate, name = 'listcreate'),
    path('list/delete/<int:id>', views.listdelete , name ='listdelete'),
    path('list/update/<int:id>', views.listupdate , name = 'listupdate'),
    # path('list/chart/', views.listchart , name = 'listchart'), 
    path('list/search/', views.listsearch , name = 'listsearch'),
    path('record/', views.record, name = 'record'),
    path('record_ajax/', views.record_ajax , name = 'record_ajax'),
    path('record/create/', views.recordcreate , name ='recordcreate'),
    path('record/delete/<int:id>', views.recorddelete , name ='recorddelete'),
    path('record/update/<int:id>', views.recordupdate , name = 'recordupdate'),
    path('record/chart/', views.recordchart , name = 'recordchart'),
    path('datatosql', views.datatosql),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'base'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.real, name = 'about'),
    path('contant/', views.hay, name = 'contact'),
]

lifemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter,url
from memorf import views as mviews
from limit import views as lview
from sport import views as sview
from on_accountapi import views as oaview
from foodrestful import views as fviews

# Router
router = DefaultRouter()

router.register(r'memorf',mviews.MemorfViewSet)
#limit
router.register(r'user',lview.UserViewSet)
router.register(r'userrole',lview.UserRoleViewSet)
#sport
router.register(r'sportitem',sview.SportItemViewSet)
router.register(r'sportrecord',sview.SportRecordViewSet)
# on_accountapi
router.register(r'on_accountapi',oaview.On_AccountapiViewSet)
#food
router.register(r'foodrestfulFC', fviews.FoodCategoryApiViewSet)
router.register(r'foodrestfulFL', fviews.FoodListApiViewSet)
# #不指定直接回傳
# router.register(r'foodrestfulDR', fviews.DietaryRecordApiViewSet)


# URL
urlpatterns = [
    #改用url指定路徑回傳指定資料，並將DietaryRecordApiViewSet當成views呼叫
    url(r'foodrestfulDR\/(?P<userid>.+)\/(?P<sdate>.+)\/(?P<edate>.+)\/$', fviews.DietaryRecordApiViewSet.as_view()),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('home.urls')),
    path('memo/', include('memo.urls')),
    path('limit/',include('limit.urls')),
    path('sport/',include('sport.urls')),
    path('on_account/', include('on_account.urls')),
    path('food/', include('food.urls')),
]

sport/urls.py
from django.urls import path
from . import views

app_name = 'sport'

urlpatterns = [

    path('',views.item, name = 'sportitem'),
    path('sportrecord/', views.record, name = 'sportrecord'),
    path('itemscraping/', views.itemScraping, name = 'itemscraping'),
    path('chartpie/', views.chartPie, name = 'chartpie'),
    path('chartdata/<str:s_date>/<str:e_date>/', views.chartData, name = 'chartdata'),
]

sport/models.py
from django.db import models
from limit.models import User

#運動項目
class SportItem(models.Model):
    name    = models.CharField(verbose_name ='運動項目', max_length=50, blank=True, null=True)
    cal     = models.DecimalField(verbose_name ='卡洛里(每小時/每公斤)', max_digits=5,decimal_places = 2)
    mdate   = models.DateTimeField(verbose_name ='修改日期', auto_now=True)
    
    state   = models.BooleanField(verbose_name ='狀態(1:啟用/0:停用)')
    cuser   = models.ForeignKey(User,models.DO_NOTHING, verbose_name ='建立人員')
    cdate   = models.DateTimeField(verbose_name ='建立日期', auto_now_add=True)
    class Meta:
        db_table = 'sport_sportitem'

#運動管理
class SportRecord(models.Model):
    sportid = models.ForeignKey(SportItem,models.DO_NOTHING, verbose_name ='運動項目')
    sdate   = models.DateField(verbose_name ='運動日期')
    duration = models.IntegerField(verbose_name ='運動持續時間(分鐘)')
    weight  = models.DecimalField (verbose_name ='體重', max_digits=4, decimal_places=1)
    cal     = models.DecimalField(verbose_name ='運動消耗卡洛里calorie',max_digits=7,decimal_places = 2) 
    cuser   = models.ForeignKey(User,models.DO_NOTHING, verbose_name ='建立人員',null=True)
    mdate   = models.DateTimeField(verbose_name ='修改日期', auto_now=True)
    
    cdate     = models.DateTimeField(verbose_name ='建立日期', auto_now_add=True)
    class Meta:
        db_table = 'sport_sportrecord'
    
#體重管理
class WeightRecord(models.Model):
    weight  = models.DecimalField (verbose_name ='體重(公斤)', max_digits=4, decimal_places=1)
    
    cuser   = models.ForeignKey(User,models.DO_NOTHING, verbose_name ='建立人員')
    cdate   = models.DateTimeField(verbose_name ='建立日期', auto_now_add=True)
    mdate   = models.DateTimeField(verbose_name ='修改日期', auto_now=True)
    class Meta:
        db_table = 'sport_weightrecord'

sport/views.py
from django.shortcuts import render,HttpResponse
from sport.models import SportItem, SportRecord
from sport.serializers import SportItemSerializer,SportRecordSerializer
from rest_framework import viewsets
from . import modelField
import datetime
from django.db.models import Count,Sum
import requests
import json

# =============   sport ViewSet  ===============================
# function desc. : 運動項目列表 ViewSet/
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/09/21
class SportItemViewSet(viewsets.ModelViewSet):
    queryset = SportItem.objects.all()
    serializer_class = SportItemSerializer

# function desc. : 個人運動紀錄管理 ViewSet
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/09/21
class SportRecordViewSet(viewsets.ModelViewSet):
    queryset = SportRecord.objects.all()
    serializer_class = SportRecordSerializer

# function desc. : 確認是否已經登入
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/10/07
def chklogin(request):
    if('userid' in request.session):
        global userid
        global username
        userid = request.session["userid"]
        username = request.COOKIES["name"]
        return 0
    else:
        return 1

# =============   sport page deal  ===============================
# function desc. : 運動項目列表
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/09/21
def item(request):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    title = "運動項目列表"
    sports = SportItem.objects.filter(state='1')
    fields = modelField.getField('sport','SportItem')[0:4]
    return render(request, 'sport/sportItem.html', locals())

# function desc. : 取得政府資料交易平台運動項目消耗熱量表，並更新或新增
# parameter : 
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/10/3
def itemScraping(request):
    if('userid' in request.session):
        userid = request.session["userid"]
    
    else:
        userid = '1'; username='Luffy'
    url = "https://quality.data.gov.tw/dq_download_json.php?nid=8494&md5_url=db669862c24a114b45629f6a27fd3881"
    
    try:
        r = requests.post(url)
        r.encoding = 'utf-8'
        items = r.json()
            
        for item in items:
            name =item["運動項目"]
            cal = item["消耗熱量(大卡/公斤體重/小時)"]
            sport = SportItem.objects.filter(name = name)
            if(sport):
                sport[0].cal = cal
                sport[0].save()
            else:
                SportItem.objects.create(name=name, cal=cal, state=1, cuser_id=userid)
    
    except err:
        return HttpResponse(err, content_type="text/plain")
    
    return HttpResponse(1, content_type="text/plain")

# function desc. : 個人運動紀錄管理
# parameter : id(預設:0)
# create user : Luffy Lin
# modify user : Luffy Lin
# modify date : 2018/09/21
def record(request,id = 0):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    if('userid' in request.session):
        userid = request.session["userid"]
    #測試暫時使用
    else:
        userid = '1'; username='Luffy'

    title = "個人運動紀錄管理"
    # fields = modelField.getField('sport','SportRecord')[0:8]
    
    sports = SportItem.objects.filter(state='1')
    datas = SportRecord.objects.filter(cuser=userid).order_by('-sdate')
    
    return render(request, 'sport/sportRecord.html', locals())

# # function desc. : 個人運動紀錄 - 圖表
# # parameter : id
# # create user : Luffy Lin
# # modify user : Luffy Lin
# # modify date : 2018/09/27   
def chartData(request,s_date,e_date):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    if('userid' in request.session):
        userid = request.session["userid"]
    #測試暫時使用
    else:
        userid = '1'; username='Luffy'
    datas = SportRecord.objects.filter(cuser=userid, sdate__range=(s_date, e_date)).values('sportid').annotate(dcount=Count('sportid'),dsum=Sum('duration')).values('sportid__name','dcount','dsum')
    datas = json.dumps(list(datas))
  

    return HttpResponse(datas, content_type="application/json")

# # function desc. : 個人運動紀錄 - 圖表
# # parameter : id
# # create user : Luffy Lin
# # modify user : Luffy Lin
# # modify date : 2018/09/27   
def chartPie(request):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))
    return render(request, 'sport/sportChartPie.html')

sport/templates/sport/sportChartPie.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="/static/styles/jquery-Datepicker.css">

{% endblock %}
{% block left%}
{% include "./sportNav.html" %}
{% endblock %}
{% block main %}
<div class="card-header">
    <i class="fas fa-chart-pie"></i>
    運動Pie Chart
</div>
<div class="card-body">
    <div>
        <span id="date-label-from">運動開始時間:</span><input class="date" type="text" id="s_date" />
        <span id="date-label-to">&sim;運動結束時間:<input class="date" type="text" id="e_date" />
            <br />
    </div>
    <br/>
    <div class="row">
        <div class="col-lg-7">
            <div class="card mb-3">
                <div class="card-header text-white bg-secondary">
                    <i class="fas fa-chart-bar"></i>
                    個別運動次數統計表</div>
                <div class="card-body" style="padding-left: 0px; height: 600px;" >
                    <canvas id="myBarChart" width="100%" height="100%"></canvas>
                </div>
            </div>
        </div>
        <div class="col-lg-5">
            <div class="card mb-3">
                <div class="card-header text-white bg-secondary">
                    <i class="fas fa-chart-pie"></i>
                    個別運動時間統計表</div>
                <div class="card-body" style="height: 600px;">
                    <canvas id="myPieChart" width="100%" height="100%"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/Chart.min.js' %}"></script>
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/jquery-Datepicker.js' %}"></script>
<script src="../../static/scripts/sportChartPie.js"></script>
{% endblock %}

sport/templates/sport/sportItem.html
{% extends 'base.html' %}
{% block styles %}
{% endblock %}
{% block left %}
<!-- Sidebar -->
{% include "./sportNav.html" %}
{% endblock %}
{% block main %}
<div class="card-header">
  <i class="fa fa-table"></i>
  運動項目
  <div style="width: 90%; display:inline-block; text-align: right; "><button id='update'><i class="fas fa-cloud-download-alt"
        style="color: Dodgerblue;"></i>政府資料交易平台更新</button></div>
</div>
<div class="card-body">
  <!-- 表格 -->
  <div class="table-responsive">
    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
      <!-- 表頭 -->
      <thead>
        <tr>
          {% for f in fields %}
          {% if forloop.first %}
          <th hidden>{{ f }}</th>
          {% else %}
          <th>{{ f }}</th>
          {% endif %}
          {% endfor %}
        </tr>
      </thead>
      <!-- 表尾 -->
      <tfoot>
        <tr>
          {% for f in fields %}
          {% if forloop.first %}
          <th hidden>{{ f }}</th>
          {% else %}
          <th>{{ f }}</th>
          {% endif %}
          {% endfor %}
        </tr>
      </tfoot>
      <tbody>

        {% for row in sports %}
        <tr>
          <td name='id' hidden>{{ row.id }}</td>
          <td>{{ row.name }}</td>
          <td>{{ row.cal }}</td>
          <td>{{row.mdate|date:"Y-m-d h:m:s"}}</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>

</div>
{% endblock %}

{% block scripts %}
{% load static %}
<script src="../../static/scripts/sportItem.js"></script>
<script src="{% static 'scripts/jquery-dateformat.min.js'%}"></script>

{% endblock %}

sport/templates/sport/sportNav.html
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa fa-fw fa-home"></i>
            <span>首頁</span>
        </a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'sport:sportrecord' %}">
            <i class="fa fa-fw fa-walking"></i>
            <span>運動紀錄</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'sport:sportitem' %}">
            <i class="fab fa-fw fa-free-code-camp"></i>
            <span>運動消耗熱量資訊</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'sport:chartpie' %}">
            <i class="fa fa-fw fa-chart-pie"></i>
            <span>運動報表</span></a>
    </li>
</ul>

sport/templates/sport/sportRecord.html
{% extends 'base.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="/static/styles/jquery-Datepicker.css">
{% endblock %}

{% block left %}
<!-- Sidebar -->
{% include "./sportNav.html" %}
{% endblock %}

{% block main %}
<div class="card-header">
  <i class="fa fa-table"></i> 運動記錄
  <div style="width: 90%; display:inline-block; text-align: right; "><i id='add' class="fas fa-plus-circle fa-2x" style="color: Dodgerblue;"></i>新增</div>
</div>
<div class="card-body">
  <div class="table-responsive">
    <!-- 運動日期區間過濾datepicker -->
    <p id="date_filter">
      <span id="date-label-from">運動開始時間:</span><input class="date" type="text" id="datepicker_from" />
      <span id="date-label-to">&sim;運動結束時間:<input class="date" type="text" id="datepicker_to" />
    </p>
    <!-- 表格 -->
    <table class="table table-bordered" id="dataTable" width="120%" cellspacing="0">
      <!-- 表頭 -->
      <thead>
        <tr>
          <th hidden>ID</th>
          <th hidden>運動編號</th>
          <th>運動項目</th>
          <th>運動日期</th>
          <th>運動時間(分)</th>
          <th>體重</th>
          <th hidden>單位卡洛里</th>
          <th>消耗卡洛里</th>
          <th hidden>建立人員編號</th>
          <th>建立人員</th>
          <th>修改日期</th>
          <th>編輯</th>
        </tr>
      </thead>
      <!-- 表尾 -->
      <tfoot>
        <tr>
          <th hidden>ID</th>
          <th hidden>運動編號</th>
          <th>運動項目</th>
          <th>運動日期</th>
          <th>運動時間(分)</th>
          <th>體重</th>
          <th hidden>單位卡洛里</th>
          <th>消耗卡洛里</th>
          <th hidden>建立人員編號</th>
          <th>建立人員</th>
          <th>修改日期</th>
          <th>編輯</th>
        </tr>
      </tfoot>
      <!-- 表身 -->
      <tbody>
        {% for row in datas %}
        <tr>
          <td name='id' hidden>{{ row.id }}</td>
          <td name='sportid' hidden>{{row.sportid.id}}</td>
          <td name='sportname'>{{row.sportid.name}}</td>
          <td name='sdate'>{{row.sdate|date:"Y-m-d"}}</td>
          <td name='duration'>{{ row.duration }}</td>
          <td name='weight'>{{ row.weight }}</td>
          <td name='unitcal' hidden>{{ row.sportid.cal }}</td>
          <td name='cal'>{{ row.cal }}</td>
          <td name='cuser' hidden>{{ row.cuser.id }}</td>
          <td name='cusername'>{{ row.cuser.name }}</td>
          <td name='mdate'>{{row.mdate|date:"Y-m-d H:i:s"}}</td>
          <td><i id="edit" class="far fa-edit"></i><i id="delete" class="far fa-trash-alt" style='color: tomato;'></i></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<div id="template" hidden>
  <select id='sportid' name='sportid' class="datas">
    <option name='sportname' value="0">請選</option>
    {% for op in sports %}
    <option name='sportname' value={{op.id}}>{{op.name}}</option>
    {% endfor %}
  </select>
  <label id='cuser'>{{userid}}</label>
  <label id='cusername'>{{username}}</label>
  </td>
</div>
{% endblock %}


{% block scripts %}
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/jquery-Datepicker.js' %}"></script>
<script src="{% static 'scripts/jquery-dateformat.min.js' %}"></script>
<script src="../../static/scripts/sportRecord.js"></script>
{% endblock %}