food/urls.py
from django.urls import path
from . import views
app_name = 'food'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('list/', views.list, name = 'list'),
    path('list/create/', views.listcreate, name = 'listcreate'),
    path('list/delete/<int:id>', views.listdelete , name ='listdelete'),
    path('list/update/<int:id>', views.listupdate , name = 'listupdate'),
    # path('list/chart/', views.listchart , name = 'listchart'), 
    path('list/search/', views.listsearch , name = 'listsearch'),
    path('record/', views.record, name = 'record'),
    path('record_ajax/', views.record_ajax , name = 'record_ajax'),
    path('record/create/', views.recordcreate , name ='recordcreate'),
    path('record/delete/<int:id>', views.recorddelete , name ='recorddelete'),
    path('record/update/<int:id>', views.recordupdate , name = 'recordupdate'),
    path('record/chart/', views.recordchart , name = 'recordchart'),
    path('datatosql', views.datatosql),
]

home/urls.py
from django.urls import path
from home import views
app_name = 'base'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('about/', views.real, name = 'about'),
    path('contant/', views.hay, name = 'contact'),
]

lifemanager/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter,url
from memorf import views as mviews
from limit import views as lview
from sport import views as sview
from on_accountapi import views as oaview
from foodrestful import views as fviews

# Router
router = DefaultRouter()

router.register(r'memorf',mviews.MemorfViewSet)
#limit
router.register(r'user',lview.UserViewSet)
router.register(r'userrole',lview.UserRoleViewSet)
#sport
router.register(r'sportitem',sview.SportItemViewSet)
router.register(r'sportrecord',sview.SportRecordViewSet)
# on_accountapi
router.register(r'on_accountapi',oaview.On_AccountapiViewSet)
#food
router.register(r'foodrestfulFC', fviews.FoodCategoryApiViewSet)
router.register(r'foodrestfulFL', fviews.FoodListApiViewSet)
# #不指定直接回傳
# router.register(r'foodrestfulDR', fviews.DietaryRecordApiViewSet)


# URL
urlpatterns = [
    #改用url指定路徑回傳指定資料，並將DietaryRecordApiViewSet當成views呼叫
    url(r'foodrestfulDR\/(?P<userid>.+)\/(?P<sdate>.+)\/(?P<edate>.+)\/$', fviews.DietaryRecordApiViewSet.as_view()),
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('', include('home.urls')),
    path('memo/', include('memo.urls')),
    path('limit/',include('limit.urls')),
    path('sport/',include('sport.urls')),
    path('on_account/', include('on_account.urls')),
    path('food/', include('food.urls')),
]

memo/urls.py
from django.urls import path
from memo import views

app_name='memo'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('update/<int:id>',views.update,name='update'),
    path('archive/',views.archive,name='archive'),
    path('chartpie/', views.chartPie, name = 'chartpie'),
    path('chartdata/<str:s_date>/<str:e_date>/', views.chartData, name = 'chartdata'),
]

memo/models.py
from django.db import models

# class Memo(models.Model):
#     # cuser = models.ForeignKey(user,models.DO_NOTHING,db_column='id')
#     memoID = models.AutoField(primary_key=True)
#     memoTitle = models.CharField(max_length=60)
#     memoContent = models.CharField(max_length=300,null=True,blank=True)
#     memoState = models.CharField(max_length=1)
#     expiredate = models.DateField(null=True)
#     createTime = models.DateTimeField(auto_now_add=True)
#     lastUpgradeT = models.DateTimeField(auto_now=True)

#     class Meta:
#         db_table = 'Memos'

memo/views.py
from django.shortcuts import render,redirect,HttpResponse
from memorf.models import Memorf
from limit.models import User
from django.db.models import F
import datetime


def chklogin(request):
    if('userid' in request.session):
        global userid
        global username
        userid = request.session["userid"]
        username = request.COOKIES["name"]
        return 0
    else:
        return 1

def index(request):
    # function desc. : 確認使用者是否登入
    # parameter : 
    # create user : Luffy Lin
    # modify user : Luffy Lin
    # modify date : 2018/10/07
    
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))

    # asc(nulls_last=True)
    memot = Memorf.objects.filter(memoState='t',cuser=userid).order_by(F('expiredate').asc(nulls_last=True))
    memod = Memorf.objects.filter(memoState='d',cuser=userid).order_by(F('expiredate').asc(nulls_last=True))
    memof = Memorf.objects.filter(memoState='f',cuser=userid).order_by(F('expiredate').asc(nulls_last=True))
    user = User.objects.get(id=userid)
    today = datetime.date.today()
    

    if request.method == 'POST':
        memoTitle = request.POST['createTit']
        memoContent = request.POST['createCon']
        expiredate = None
        if request.POST['createED']:
            expiredate = request.POST['createED']
        print(userid)
        print(type(userid))
        Memorf.objects.create(memoTitle=memoTitle,memoContent=memoContent,expiredate=expiredate,memoState='t',cuser=user)
        return redirect('/memo')

    return render(request,'memo/index.html',locals())

def update(request,id):
    memo = Memorf.objects.get(memoID=id)
    memo.memoTitle = request.POST['memoTitle']
    memo.memoContent = request.POST['memoContent']
    memo.memoState = request.POST['memoState']

    if request.POST['expiredate']:
        memo.expiredate = request.POST['expiredate']

    memo.save()

    return redirect('/memo')

def archive(request):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))
    
    memoa = Memorf.objects.filter(memoState='a',cuser=userid).order_by(F('expiredate').asc(nulls_last=True))
    return render(request,'memo/archive.html',locals())

# # function desc. : 個人運動紀錄 - 圖表
# # parameter : id
# # create user : Luffy Lin
# # modify user : Luffy Lin
# # modify date : 2018/09/27   
def chartData(request,s_date,e_date):

    userid = request.session["userid"]
    user = User.objects.get(id=userid)
    
    # count = Memorf.objects.filter(cuser=userid, expiredate__range=(s_date, e_date)).values('memoState').annotate(dcount=Count('memoState')).values('memoState','dcount')
    tasks = Memorf.objects.filter(cuser=user,expiredate__range=(s_date, e_date))

    archive = Memorf.objects.filter(cuser=user,memoState='a',expiredate__range=(s_date, e_date)).count()
    finish = Memorf.objects.filter(cuser=user,memoState='f',expiredate__range=(s_date, e_date)).count()
    todo = tasks.exclude(memoState='f').exclude(memoState='a')
   
    today = datetime.date.today()
    overdue = 0
    for task in todo:
        if task.expiredate < today:
            overdue += 1
    
    todoc = todo.count() - overdue
    count = str([todoc, finish, archive, overdue])
    # count = json.dumps(count)
    return HttpResponse(count, content_type="text/plain")

def chartPie(request):
    if chklogin(request):
        path = request.path
        return HttpResponse("<script>alert('請先登入');location.href = '/limit/login?url={}'</script>".format(path))
    return render(request, 'memo/memoChartPie.html')

memo/templates/memo/archive.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles/memocss.css' %}">

{% endblock %}

{% block left %}
{% include "./memoNav.html" %}
{% endblock %}

{% block main %}

<div class='searchDiv'>
    <form>
        <div>
            <input type="text" class="searchtext" placeholder="Search">
            <img style='cursor:pointer;' id='searchbtn'src='/static/images/search.png'>
        </div>
    </form>
</div>
<div class='body'>

    <div class='mainblock'>
        <div class='inBlock'>       
            <div class='blockTi'>  
                <span>封存</span>           
            </div>
            
            <div class='blockCon' id='bct'>
                {% for memo in memoa %}
                    <div class='cardblock'>
                        <div class='card' id='card{{ memo.memoID }}'>
                            <div class='cardTi'>
                                <p class='cardTitle'>{{ memo.memoTitle }}</p>    
                                <i class="fas fa-stream"></i>
                            </div>
                            <div name='cardContent' class='cardCon'>
                                <div name='content'>{{ memo.memoContent }}</div>
                                <div style="text-align: right">
                                    <p>{{ memo.expiredate }}</p>
                                    <input name='update' type="button" class="btn btn-light btn-sm" value='修改'>
                                    <input id='delete{{ memo.memoID }}' name='delete' type="button" class="btn btn-light btn-sm" value='刪除'>
                                </div>
                            </div>                        
                        </div>
                        <div class='manage'>
                            <form method='POST' action='/memo/update/{{ memo.memoID }}'>
                                {% csrf_token %}
                                <div><input type='text' value='{{ memo.memoTitle }}' name='memoTitle' style='width:100%'></div>
                                <div><textarea style='width:100%' name='memoContent'>{{ memo.memoContent }}</textarea></div>
                                <div><select name='memoState'>
                                        <option value='t'>代辦</option>
                                        <option value='d'>進行中</option>
                                        <option value='f'>完成</option>
                                        <option value='a' selected>封存</option>
                                    </select>
                                    <label>預計完成日期</label>
                                    <input type="date" name='expiredate' value="{{ memo.expiredate|date:'Y-m-d' }}">
                                </div>
                                <div style='text-align: right'>
                                    <input name='cancel' type='button' class='btn btn-light btn-sm' value='取消'>
                                    <input type='submit' class='btn btn-light btn-sm' value='確認修改'>
                                </div>
                                
                            </form>
                        </div>
                    </div> 
                    
                {% endfor %}     
            </div>
        </div>        
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="/static/scripts/jquery-3.3.1.min.js"></script>
<script src="{% static 'scripts/memojs.js' %}"></script>
<script src="{% static 'scripts/Chart.min.js' %}"></script>
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/jquery-Datepicker.js' %}"></script>
<script src="{% static 'scripts/memoChartPie.js' %}"></script>
<script type="text/javascript">
  // using jQuery
  var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
</script>

{% endblock %}

memo/templates/memo/index.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'styles/memocss.css' %}">

{% endblock %}

{% block left %}
{% include "./memoNav.html" %}
{% endblock %}

{% block main %}

<div class='searchDiv'>
    <form>
        <div>
            <input type="text" class="searchtext" placeholder="Search">
            <img style='cursor:pointer;' id='searchbtn'src='/static/images/search.png'>
        </div>
    </form>
</div>
<div class='body'>

    <div class='mainblock'>
        <div class='inBlock' id='t'>       
            <div class='blockTi'>  
                <span>待辦事項</span>
                <button id='createCard' style="float:right" type="button" class="btn btn-light btn-sm">新增</button>            
            </div>
            
            <div class='blockCon' id='bct'>
                {% for memo in memot %}
                    <div class='cardblock'>
                        <div class='card' id='card{{ memo.memoID }}'>
                            <div class='cardTi'>
                                {% if memo.expiredate < today %}
                                <p class='cardTitle' style="color:red">{{ memo.memoTitle }}</p>    
                                <i class="fas fa-stream"></i>
                            </div>
                            <div name='cardContent' class='cardCon'>
                                <div name='content' style="color:red">{{ memo.memoContent }}</div>
                                <div style="text-align: right">
                                    <p style="color:red">{{ memo.expiredate }}</p>
                                {% else %}
                                <p class='cardTitle'>{{ memo.memoTitle }}</p>    
                                <i class="fas fa-stream"></i>
                            </div>
                            <div name='cardContent' class='cardCon'>
                                <div name='content'>{{ memo.memoContent }}</div>
                                <div style="text-align: right">
                                    <p>{{ memo.expiredate }}</p>
                                    {% endif %}
                                    <input id='archive{{ memo.memoID }}' name='archive' type="button" class="btn btn-light btn-sm" value='封存'>
                                    <input name='update' type="button" class="btn btn-light btn-sm" value='修改'>
                                    <input id='delete{{ memo.memoID }}' name='delete' type="button" class="btn btn-light btn-sm" value='刪除'>
                                </div>
                            </div>                        
                        </div>

                        <div class='manage'>
                            <form method='POST' action='/memo/update/{{ memo.memoID }}'>
                                {% csrf_token %}
                                <div><input type='text' value='{{ memo.memoTitle }}' name='memoTitle' style='width:100%' required></div>
                                <div><textarea style='width:100%' name='memoContent'>{{ memo.memoContent }}</textarea></div>
                                <div><select name='memoState'>
                                        <option value='t' selected>代辦</option>
                                        <option value='d'>進行中</option>
                                        <option value='f'>完成</option>
                                        <option value='a'>封存</option>
                                    </select>
                                    <label>預計完成日期</label>
                                    <input type="date" name='expiredate' value="{{ memo.expiredate|date:'Y-m-d' }}">
                                </div>

                                <div style='text-align: right'>
                                    <input name='cancel' type='button' class='btn btn-light btn-sm' value='取消'>
                                    <input type='submit' class='btn btn-light btn-sm' value='確認修改'>
                                </div>
                            </form>
                        </div>
                    </div> 
                {% endfor %}
                

                    <div id='iF' class='iF'>
                        <form method="POST">
                            {% csrf_token %}
                            <div>
                                <input type='text' name='createTit' style='width:100%' placeholder="請輸入標題" required>
                            </div>
                            <div>
                                <textarea style='width:100%' name='createCon' placeholder="請輸入內容"></textarea>
                            </div>
                            <div>
                                <label>預計完成日期</label>
                                <input type="date" name='createED'>
                            </div>
                            <div style='text-align: right'>
                                <input id='iFcancel' type='button' class='btn btn-light btn-sm' value='取消'>
                                <input id='createbtn' type='submit' class="btn btn-light btn-sm" value='送出'>
                            </div>
                        </form>
                    </div>              
            </div>
        </div>        
    </div>

    <div class='mainblock'>
        <div class='inBlock' id='d'>
        
            <div class='blockTi'>  
                <span>進行中</span>             
            </div>
                
            <div class='blockCon' id='bcd'>
                {% for memo in memod %}
                    <div class='cardblock'>
                        <div class='card' id='card{{ memo.memoID }}'>
                            <div class='cardTi'>
                                {% if memo.expiredate < today %}
                                <p class='cardTitle' style="color:red">{{ memo.memoTitle }}</p>    
                                <i class="fas fa-stream"></i>
                            </div>
                            <div name='cardContent' class='cardCon'>
                                <div name='content' style="color:red">{{ memo.memoContent }}</div>
                                <div style="text-align: right">
                                    <p style="color:red">{{ memo.expiredate }}</p>
                                {% else %}
                                <p class='cardTitle'>{{ memo.memoTitle }}</p>    
                                <i class="fas fa-stream"></i>
                            </div>
                            <div name='cardContent' class='cardCon'>
                                <div name='content'>{{ memo.memoContent }}</div>
                                <div style="text-align: right">
                                    <p>{{ memo.expiredate }}</p>
                                    {% endif %}
                                    <input id='archive{{ memo.memoID }}' name='archive' type="button" class="btn btn-light btn-sm" value='封存'>
                                    <input name='update' type="button" class="btn btn-light btn-sm" value='修改'>
                                    <input id='delete{{ memo.memoID }}' name='delete' type="button" class="btn btn-light btn-sm" value='刪除'>
                                </div>
                            </div>
                        </div>

                        <div class='manage'>
                            <form method='POST' action='/memo/update/{{ memo.memoID }}'>
                                {% csrf_token %}
                                <div><input type='text' value='{{ memo.memoTitle }}' name='memoTitle' style='width:100%' required></div>
                                <div><textarea style='width:100%' name='memoContent'>{{ memo.memoContent }}</textarea></div>
                                <div><select name='memoState'>
                                        <option value='t'>代辦</option>
                                        <option value='d' selected>進行中</option>
                                        <option value='f'>完成</option>
                                        <option value='a'>封存</option>
                                    </select>
                                    <label>預計完成日期</label>
                                    <input type="date" name='expiredate' value="{{ memo.expiredate|date:'Y-m-d' }}">
                                </div>
                                
                                <div style='text-align: right'>
                                    <input name='cancel' type='button' class='btn btn-light btn-sm' value='取消'>
                                    <input type='submit' class='btn btn-light btn-sm' value='確認修改'>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>                            
         </div>   
    </div>

    <div class='mainblock'>
        <div class='inBlock' id='f'>
        
            <div class='blockTi'>  
                <span>已完成</span>          
            </div>
                
            <div class='blockCon' id='bcf'>
                {% for memo in memof %}
                <div class='cardblock'>
                    <div class='card' id='card{{ memo.memoID }}'>
                        <div class='cardTi'>
                            <p class='cardTitle'>{{ memo.memoTitle }}</p>
                            <i class="fas fa-stream"></i>
                        </div>
                        <div name='cardContent' class='cardCon'>
                            <div name='content'>{{ memo.memoContent }}</div>
                            <div style="text-align: right">
                                <p>{{ memo.expiredate }}</p>
                                <input id='archive{{ memo.memoID }}' name='archive' type="button" class="btn btn-light btn-sm" value='封存'>
                                <input name='update' type="button" class="btn btn-light btn-sm" value='修改'>
                                <input id='delete{{ memo.memoID }}' name='delete' type="button" class="btn btn-light btn-sm" value='刪除'>
                            </div>
                        </div>
                    </div>

                    <div class='manage'>
                        <form method='POST' action='/memo/update/{{ memo.memoID }}'>
                            {% csrf_token %}
                            <div><input type='text' value='{{ memo.memoTitle }}' name='memoTitle' style='width:100%' required></div>
                            <div><textarea style='width:100%' name='memoContent'>{{ memo.memoContent }}</textarea></div>
                            <div><select name='memoState'>
                                    <option value='t'>代辦</option>
                                    <option value='d'>進行中</option>
                                    <option value='f' selected>完成</option>
                                    <option value='a'>封存</option>
                                </select>
                                <label>預計完成日期</label>
                                <input type="date" name='expiredate' value="{{ memo.expiredate|date:'Y-m-d' }}">
                            </div>
                            <div style='text-align: right'>
                                <input name='cancel' type='button' class='btn btn-light btn-sm' value='取消'>
                                <input type='submit' class='btn btn-light btn-sm' value='確認修改'>
                            </div>
                            
                        </form>
                    </div>
                </div>
                {% endfor %}
            </div>                            
        </div>   
    </div>

</div>
{% endblock %}

{% block scripts %}
<script src="/static/scripts/jquery-3.3.1.min.js"></script>
<script src="{% static 'scripts/drag.js' %}"></script>
<script src="{% static 'scripts/memojs.js' %}"></script>

{% endblock %}

memo/templates/memo/memoChartPie.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="/static/styles/jquery-Datepicker.css">

{% endblock %}

{% block left %}
{% include "./memoNav.html" %}
{% endblock %}

{% block main %}
<div class="card-header">
    <i class="fas fa-chart-pie"></i>
    待辦事項Pie Chart
</div>
<div class="card-body">
    <div>
        <span id="date-label-from">查詢起始日期:</span><input class="date" type="text" id="s_date" />
        <span id="date-label-to">&sim;查詢結束時間:<input class="date" type="text" id="e_date" />
            <br />
    </div>
    <br/>
    <div class="row">
        <div class="col-lg-5">
            <div class="card mb-3">
                <div class="card-header text-white bg-secondary">
                    <i class="fas fa-chart-pie"></i>
                    待辦事項統計圖</div>
                <div id ='Pie' class="card-body" style="height: 600px;">
                    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/Chart.min.js' %}"></script>
<script src="{% static 'scripts/moment.min.js' %}"></script>
<script src="{% static 'scripts/jquery-Datepicker.js' %}"></script>
<script src="{% static 'scripts/memoChartPie.js' %}"></script>

{% endblock %}

memo/templates/memo/memoNav.html
<ul class="sidebar navbar-nav">
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'base:index' %}">
            <i class="fa fa-fw fa-home"></i>
            <span>首頁</span>
        </a>
    </li>

    <li class="nav-item active">
        <a class="nav-link" href="{% url 'memo:index' %}">
            <i class="fa fa-fw fa-list"></i>
            <span>待辦事項</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'memo:archive' %}">
            <i class="fa fa-fw fa-archive"></i>
            <span>封存</span></a>
    </li>
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'memo:chartpie' %}">
            <i class="fa fa-fw fa-chart-pie"></i>
            <span>統計圖表</span></a>
    </li>
</ul>